DROP DATABASE IF EXISTS testshop;
CREATE DATABASE testshop;
USE testshop;
CREATE TABLE CUSTOMERS (
  ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(20)        NOT NULL,
  LAST_NAME  VARCHAR(20),
  ADDRESS   VARCHAR(100),
  PHONE     VARCHAR(13),
  EMAIL     VARCHAR(30) UNIQUE NOT NULL,
  PASSWORD  VARCHAR(10)        NOT NULL
);
CREATE TABLE PRODUCTS (
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE       VARCHAR(20)   NOT NULL,
  PRICE       DOUBLE(10, 2) NOT NULL,
  QUANTITY    INT(10)       NOT NULL,
  DESCRIPTION VARCHAR(250)
);
CREATE TABLE SELLERS (
  ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME  VARCHAR(20) NOT NULL,
  EMAIL     VARCHAR(30) NOT NULL UNIQUE,
  PHONE     VARCHAR(13) NOT NULL UNIQUE,
  PASSWORD  VARCHAR(20) NOT NULL
);
CREATE TABLE ORDERS (
  ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID BIGINT      NOT NULL,
  DATE_ORDER  DATE        NOT NULL,
  SELLER_ID   BIGINT      NOT NULL,
  STATUS     VARCHAR(10) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
  FOREIGN KEY (SELLER_ID) REFERENCES SELLERS (ID)
);
CREATE TABLE PRODUCTS_SOLD (
  ORDER_ID   BIGINT        NOT NULL,
  TITLE     VARCHAR(250)  NOT NULL,
  QUANTITY  INT(10)       NOT NULL,
  PRICE     DOUBLE(10, 2) NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
  );
CREATE TABLE COMMENTS (
  ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID    BIGINT       NOT NULL,
  CUSTOMER_ID   BIGINT       NOT NULL,
  CUSTOMER_NAME VARCHAR(20)  NOT NULL,
  CONTENT      VARCHAR(250) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
);
