INSERT INTO USERS (FIRST_NAME, LAST_NAME, ADDRESS, PHONE, EMAIL, PASSWORD)
VALUES ("chuck", "norris", "USA", "1234", "chuck@norris.us", "ranger");
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ADDRESS, PHONE, EMAIL, PASSWORD)
VALUES ("bruce", "lee", "China", "2345", "bruce@lee", "kee-ya");
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ADDRESS, PHONE, EMAIL, PASSWORD)
VALUES ("vasily", "terkin", "Russia", "3456", "vasily@terkin.ru", "bear");
INSERT INTO PRODUCTS (TITLE, PRICE, QUANTITY, DESCRIPTION)
VALUES ("product", "1.00", "5", "description product 1");
INSERT INTO PRODUCTS (TITLE, PRICE, QUANTITY, DESCRIPTION)
VALUES ("", "product", "2.00", "5", "description product 1");
INSERT INTO PRODUCTS (TITLE, PRICE, QUANTITY, DESCRIPTION)
VALUES ("product 3", "3.00", "5", "description product 1");
INSERT INTO SELLERS (FIRST_NAME, LAST_NAME, PHONE, EMAIL, PASSWORD)
VALUES ("seller 1", "seller 1", "4321", "seller@1.mail", "seller1");
INSERT INTO SELLERS (FIRST_NAME, LAST_NAME, PHONE, EMAIL, PASSWORD)
VALUES ("seller 2", "seller 2", "5432", "seller@2.mail", "seller2");
INSERT INTO ORDERS (CUSTOMER_ID, SELLER_ID, DATE_ORDER, STATUS)
VALUES ("1", "1", "2015-02-12", "sold");
INSERT INTO ORDERS (CUSTOMER_ID, SELLER_ID, DATE_ORDER, STATUS)
VALUES ("2", "1", "2015-02-13", "sold");
INSERT INTO ORDERS (CUSTOMER_ID, SELLER_ID, DATE_ORDER, STATUS)
VALUES ("2", "1", "2015-02-14", "check");
INSERT INTO PRODUCTS_SOLD (ORDER_ID, TITLE, QUANTITY, PRICE)
VALUES ("1", "1", "1", "1.00");
INSERT INTO PRODUCTS_SOLD (ORDER_ID, TITLE, QUANTITY, PRICE)
VALUES ("2", "1", "2", "1.00");
INSERT INTO COMMENTS (CUSTOMER_ID, PRODUCT_ID, CUSTOMER_NAME, CONTENT)
VALUES ("1", "1", "chuck", "content1chuk");
INSERT INTO COMMENTS (CUSTOMER_ID, PRODUCT_ID, CUSTOMER_NAME, CONTENT)
VALUES ("1", "2", "chuck", "content2chuk");
INSERT INTO COMMENTS (CUSTOMER_ID, PRODUCT_ID, CUSTOMER_NAME, CONTENT)
VALUES ("2", "1", "bruce", "content1bruce");
